import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCESSED = 'ACCESSED',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

@Schema({ timestamps: true })
export class ExamInvitation extends Document {
  @Prop({ required: true, unique: true })
  invitationToken: string; // UUID v4 token

  @Prop({ type: Types.ObjectId, ref: 'Exam', required: true })
  examId: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'Organization', required: true })
  organizationId: Types.ObjectId;

  // Candidate information (no User account created)
  @Prop({ required: true, lowercase: true })
  candidateEmail: string;

  @Prop({ required: true })
  candidateName: string;

  @Prop()
  candidatePhone?: string;

  // Invitation lifecycle
  @Prop({ type: String, enum: InvitationStatus, default: InvitationStatus.PENDING })
  status: InvitationStatus;

  @Prop({ required: true })
  expiresAt: Date; // Token expiration (e.g., 7 days from creation)

  @Prop({ default: 0 })
  accessCount: number; // Track how many times the link was accessed

  @Prop()
  firstAccessedAt?: Date;

  @Prop()
  examStartedAt?: Date;

  @Prop()
  examCompletedAt?: Date;

  // Link to exam session once started
  @Prop({ type: Types.ObjectId, ref: 'ExamSession' })
  sessionId?: Types.ObjectId;

  // Link to result once completed
  @Prop({ type: Types.ObjectId, ref: 'Result' })
  resultId?: Types.ObjectId;

  // Metadata
  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  invitedBy: Types.ObjectId; // ORG_ADMIN or RECRUITER who sent invitation

  @Prop()
  invitationNote?: string; // Custom message to candidate

  @Prop()
  revokedAt?: Date;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  revokedBy?: Types.ObjectId;

  @Prop()
  revocationReason?: string;

  // Timestamps (auto-generated by Mongoose with timestamps: true)
  createdAt: Date;
  updatedAt: Date;
}

export const ExamInvitationSchema = SchemaFactory.createForClass(ExamInvitation);

// Indexes
ExamInvitationSchema.index({ invitationToken: 1 }, { unique: true });
ExamInvitationSchema.index({ examId: 1, candidateEmail: 1 });
ExamInvitationSchema.index({ status: 1, expiresAt: 1 });
ExamInvitationSchema.index({ organizationId: 1, examId: 1 });
ExamInvitationSchema.index({ candidateEmail: 1 });
